name: Notify Telegram

on:
  deployment_status:

jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
    - name: Notify Telegram
      run: |
        curl -X POST "https://api.telegram.org/bot${{ 6220773573:AAFgZyQIzZoHTvOM028PHgpn47rc0kUv4rI }}/sendMessage" \
        -d chat_id=${{ 550102194 }} \
        -d text="Deployment finished successfully on Vercel."
